### ISSUE TITLE
Edit, Cancel, Save Button

### ISSUE THREAD

**Issue by Danish-Ali097** [nathancahill/table-edits#5]
hi, the documentaion shows that we can use button to edit cancel a row data but their is no Cancel Button, how can i fix this

**Comment by Danish-Ali097** [comment]
https://github.com/Danish-ali097/table-edits (Some Modification)

**Comment by thatal** [comment]
@Danish-Ali097  is your repo is capable of cancel button, and custom filed type ?

**Comment by Danish-Ali097** [comment]
No i didnot do that

**Comment by Danish-Ali097** [comment]
For the cancel button yes

**Comment by Danish-Ali097** [comment]
> @Danish-Ali097 is your repo is capable of cancel button, and custom filed type 

i modify the repository to add boorstraped text fields, select tags, i also have a functionality of only edit one row at a time
